# Python's scientific libraries

Following is my attempt to interactively learn how to use popular libraries like numpy, scipy, matplotlib, etc. I will code and try to explore various APIs provided by these awesome libraries.

## What is NumPy?

NumPy is a python library for scientific computations. It provides multidimensional array support with fast operarions on it using compiled C code. NumPy arrays are instances of `ndarray` which are homogenous multidimensional arrays.

## Features of NumPy

1. ##### Vectorization
In numpy, most of the code resembles standard mathematical operations rather than be composed of messy `for loops`. For example, the product of two arrays in numpy is taken as follows:
$$c = a * b$$
Where c is the resultant array with $c[i] = a[i] * b[i]$.
2. ##### Broadcasting
Operations in numpy are of implicit element by element type as seen above. It refers to how numpy performs operations between arrays of different shapes. To do this, numpy broadcasts the smaller array to make it compatible with the larger one following the rules mentioned [here][1].

[1]: https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#module-numpy.doc.broadcasting

## Terminologies

1. NumPy arrays known as ndarray are also aliased by the name **array**.
2. The dimensions are referred to as **axes**.
3. An array that refers to another array’s data instead is called a **view**. For example, we may create a view that only shows every second element of another array. It is better known as shallow copy to Java programmers. This is akin to SQL's views.
4. Any sequence that can be interpreted as an ndarray is called **array_like**. This includes nested lists, tuples, scalars and existing arrays.
5. **C type** array are stored as row major. **Fortran type** arrays are the opposite, stored as column major. In row major form, the rightmost index/dimension refers to the integers stored in the array

## Basics
Let's start with some basic code.

In [1]:
import numpy as np
a = np.array([1, 2, 4])
a

array([1, 2, 4])

In [2]:
a.shape, a.ndim, a.size, a.dtype, a.itemsize, a.data # attributes of ndarray class

((3,), 1, 3, dtype('int64'), 8, <memory at 0x7f3adc455048>)

In [3]:
type(a)

numpy.ndarray

### Creating Arrays

In [4]:
b = np.array([             # a 2-d array
    [1, 3, 4], [1, 0 , -1] # np data types include intx, floatx, uintx (unsigned), bool_, 
], dtype = np.int8)        # complex64, complex128; where x is number of bits per element: 8, 16, ...
                           

In [5]:
b.shape, b.size, b.itemsize

((2, 3), 6, 1)

In [6]:
np.zeros([2,3]) # creates a 2 x 3 array and fills it with 0s with dtype = float64

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones([1, 7], dtype = np.bool_)

array([[ True,  True,  True,  True,  True,  True,  True]])

In [8]:
np.empty([1, 3]) # randomly initialized contents

array([[2.75859453e-313, 1.43279037e-322, 4.65231435e-310]])

In [9]:
np.arange(23) == np.array(range(23)) # arange() creates array similar to python's range

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

^Even the comparison operation is vectorized...

To have a normal comparison, we can use `all` function

In [10]:
np.all(np.arange(23) == np.array(range(23)))

True

In [11]:
np.arange(0, 1, 0.333333333333333333) # arange unlike range accepts float arguments

array([0.        , 0.33333333, 0.66666667])

although, linspace is preferred over arange because of limitations of floating precision.

In [12]:
np.linspace(0, 1, 4) # third argument denotes the size of result array

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [13]:
np.zeros_like(b) # creates zero array with the dimensions of b

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [14]:
np.full([2, 1], 10)

array([[10],
       [10]])

In [15]:
# 2 elts in first level each of which contains 
# 4 elts each, each of which have 3 integers
# first level corresponds to axis 0, second to 
# axis 1 and so on...
np.random.rand(2, 4, 3) # np.random is pretty interesting, we'll come back to it later

array([[[0.09829473, 0.11115475, 0.91604417],
        [0.66527935, 0.03885723, 0.69493732],
        [0.53555173, 0.97023474, 0.05054188],
        [0.03954294, 0.33112942, 0.52000864]],

       [[0.87794669, 0.85581071, 0.88604739],
        [0.12829817, 0.00371892, 0.09143216],
        [0.95483109, 0.23239437, 0.11398243],
        [0.24222798, 0.59806898, 0.85572201]]])

In [16]:
def f(x, y):
    return x - y
np.fromfunction(f, (2,3), dtype = int) # create a np array from a function

array([[ 0, -1, -2],
       [ 1,  0, -1]])

In [17]:
c = np.array([
    [
        [[1, 2, 3], [9, 2, 4]],            # This shows how np arrays are printed
        [[3, 0, -1], [4, 7, -5]] 
    ],
    [
        [[5, 0, -5], [2, 1, 8]],
        [[0, 0, 1], [-15, 3, 11]]
    ]
])
print(c)
print(c.shape)

[[[[  1   2   3]
   [  9   2   4]]

  [[  3   0  -1]
   [  4   7  -5]]]


 [[[  5   0  -5]
   [  2   1   8]]

  [[  0   0   1]
   [-15   3  11]]]]
(2, 2, 2, 3)


### Operations on Arrays

As we've seen before all **binary operations** are performed **element-wise**. Let's try out a few...

In [18]:
x = 3
y = np.arange(5)
x * y                # x scaled before taking product

array([ 0,  3,  6,  9, 12])

In [19]:
x = np.linspace(4, 5, 5) - 4
x, y

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), array([0, 1, 2, 3, 4]))

In [20]:
x + y, x - y, x * y, x < y, y / 2, y ^ 1 # standard element by element operations on arrays

(array([0.  , 1.25, 2.5 , 3.75, 5.  ]),
 array([ 0.  , -0.75, -1.5 , -2.25, -3.  ]),
 array([0.  , 0.25, 1.  , 2.25, 4.  ]),
 array([False,  True,  True,  True,  True]),
 array([0. , 0.5, 1. , 1.5, 2. ]),
 array([1, 0, 3, 2, 5]))

In [21]:
x -= 1
x

array([-1.  , -0.75, -0.5 , -0.25,  0.  ])

We can do matrix multiplication using `@` operator or `dot` function.

In [22]:
np.array([[0, 1j], [1, -1j]]) @ np.array([[1], [2]])

array([[0.+2.j],
       [1.-2.j]])

We can take dot product between two vectors `a` and `b` as follows:

In [23]:
a = np.array([2, 0, 1, -1])
b = np.array([1, -1, 3, 1])
a @ b.transpose() # transpose is a unary operation discussed below

4

Next, we see how to carry out **unary operations**.

In [24]:
c

array([[[[  1,   2,   3],
         [  9,   2,   4]],

        [[  3,   0,  -1],
         [  4,   7,  -5]]],


       [[[  5,   0,  -5],
         [  2,   1,   8]],

        [[  0,   0,   1],
         [-15,   3,  11]]]])

In [25]:
c.min(), c.max(), c.sum(), c.mean(), c.std() # Unary operations on ndarray

(-15, 11, 40, 1.6666666666666667, 5.096294950473552)

We can also specify which `axis` to use to perform these unary operations. For any numpy array, `axis = 0` is the first dimension, `axis = 1` is second and so on...
If we take max over first dimension, we see that we have two 2x2x3 elements in the first dimension. So, max operation should return the max of those. Let's see how it does that.
P.S. keepdims is used to preserve the original number of dimensions.

In [26]:
m = c.max(axis = 0, keepdims = True)
print(m)
print(m.shape)

[[[[ 5  2  3]
   [ 9  2  8]]

  [[ 3  0  1]
   [ 4  7 11]]]]
(1, 2, 2, 3)


So, it compared integers in each flattened 2x2x3 elements one by one and picked the max of the two. Let's see what happens when we take max across second dimension. 

In [27]:
m = c.max(axis = 1, keepdims = True)
print(m)
print(m.shape)

[[[[ 3  2  3]
   [ 9  7  4]]]


 [[[ 5  0  1]
   [ 2  3 11]]]]
(2, 1, 2, 3)


The same thing happens, except now the integers of 2x3 array are compared piecewise.

In [28]:
c.cumsum(axis = 3) # We can take cumulative sum too

array([[[[  1,   3,   6],
         [  9,  11,  15]],

        [[  3,   3,   2],
         [  4,  11,   6]]],


       [[[  5,   5,   0],
         [  2,   3,  11]],

        [[  0,   0,   1],
         [-15, -12,  -1]]]])

NumPy also defines **Universal Functions (`ufunc`)** which takes one or two array(s) as input and output a single array containing the result of the corresponding element-wise/unary operation. Examples include `add`, `multiply`, `power`, `mod`, `vdot`, `fabs`, `sign`, `exp`, `log`, etc.

### Indexing

For most of the time, ndarrays work nicely like python lists. They can be indexed, sliced, iterated upon, etc.

In [29]:
a, b

(array([ 2,  0,  1, -1]), array([ 1, -1,  3,  1]))

In [30]:
a[1], b[2] # Indexing the array like lists

(0, 3)

In [31]:
a[1:3], b[2:] # array slicing

(array([0, 1]), array([3, 1]))

In [32]:
a[::-1] = np.arange(4) # extended slicing
b[1::2] = [10, 11] # works because list is array_like
b[0::2] = -1 # again works because scalars are array_like
a, b

(array([3, 2, 1, 0]), array([-1, 10, -1, 11]))

In [33]:
print(*a, sep = ' + ', end = " = " + str(a.sum())) # Works just as a list would

3 + 2 + 1 + 0 = 6

For multidimensional arrays, we have an index for each axis.

In [34]:
c

array([[[[  1,   2,   3],
         [  9,   2,   4]],

        [[  3,   0,  -1],
         [  4,   7,  -5]]],


       [[[  5,   0,  -5],
         [  2,   1,   8]],

        [[  0,   0,   1],
         [-15,   3,  11]]]])

In [35]:
c[1, 1, 1, 0] # the smallest element

-15

In [36]:
c[:,:,:,1].flatten() # all elements in the second column 

array([2, 2, 0, 7, 0, 1, 0, 3])

In [37]:
c[...,1].flatten() # flatten returns a copy whereas ravel avoids it if possible

array([2, 2, 0, 7, 0, 1, 0, 3])

Here 3 dots (...) represent that all indices are to be included at those positions. It's very similar to the notation of writing an IPv6 address in short form. For e.g. `c[0,:,:,1]` is equivalent to `c[0,...,1]`.

In [38]:
c[1] # equivalent to c[1,...]

array([[[  5,   0,  -5],
        [  2,   1,   8]],

       [[  0,   0,   1],
        [-15,   3,  11]]])

[np.newaxis][1] is just an alias for `None`. It allows us to add an extra dimension while slicing an array.

[1]: https://docs.scipy.org/doc/numpy/reference/constants.html#numpy.newaxis

In [39]:
c[1,..., np.newaxis] # it's the same array as above, but with an extra dimension

array([[[[  5],
         [  0],
         [ -5]],

        [[  2],
         [  1],
         [  8]]],


       [[[  0],
         [  0],
         [  1]],

        [[-15],
         [  3],
         [ 11]]]])

In [40]:
print(*c, sep = "\n" + "-"*17 + "\n") # iterating in multidimensional arrays

[[[ 1  2  3]
  [ 9  2  4]]

 [[ 3  0 -1]
  [ 4  7 -5]]]
-----------------
[[[  5   0  -5]
  [  2   1   8]]

 [[  0   0   1]
  [-15   3  11]]]


### Shape modifying operations

We can reshape the array by using `ravel`/`flatten`, `transpose` (as seen before) and `reshape`. We can also stack two arrays together.

In [41]:
c.ravel()

array([  1,   2,   3,   9,   2,   4,   3,   0,  -1,   4,   7,  -5,   5,
         0,  -5,   2,   1,   8,   0,   0,   1, -15,   3,  11])

In [42]:
c.reshape(6, 4) # returns a new array with modified shape

array([[  1,   2,   3,   9],
       [  2,   4,   3,   0],
       [ -1,   4,   7,  -5],
       [  5,   0,  -5,   2],
       [  1,   8,   0,   0],
       [  1, -15,   3,  11]])

In [43]:
c.reshape(6, -1).T # the second dimension is calculated automatically

array([[  1,   2,  -1,   5,   1,   1],
       [  2,   4,   4,   0,   8, -15],
       [  3,   3,   7,  -5,   0,   3],
       [  9,   0,  -5,   2,   0,  11]])

In [44]:
x = np.array(c) # creates a deep copy of c
x is c, x.base is c, x.flags.owndata

(False, False, True)

In [45]:
x.shape = 6, -1 # equivalent to x.resize(6, -1)
x

array([[  1,   2,   3,   9],
       [  2,   4,   3,   0],
       [ -1,   4,   7,  -5],
       [  5,   0,  -5,   2],
       [  1,   8,   0,   0],
       [  1, -15,   3,  11]])

In [46]:
a, b

(array([3, 2, 1, 0]), array([-1, 10, -1, 11]))

In [47]:
np.hstack((a,b)) # concatenates along second axis

array([ 3,  2,  1,  0, -1, 10, -1, 11])

In [48]:
np.vstack((a,b)) # concatenates along first axis

array([[ 3,  2,  1,  0],
       [-1, 10, -1, 11]])

A more general function to use is [concatenate][1].

Function [split][2] does the opposite of `stack`.

[1]: https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html#numpy.concatenate
[2]: https://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html#numpy.split

In [49]:
print(*np.hsplit(c.reshape(6, -1), 2), sep="\n")

[[  1   2]
 [  2   4]
 [ -1   4]
 [  5   0]
 [  1   8]
 [  1 -15]]
[[ 3  9]
 [ 3  0]
 [ 7 -5]
 [-5  2]
 [ 0  0]
 [ 3 11]]


The function [column_stack][1] takes as i/p a tuple of 1D arrays and outputs a 2D array with it's column vectors as the original 1D arrays.

[1]: https://docs.scipy.org/doc/numpy/reference/generated/numpy.column_stack.html#numpy.column_stack

In [50]:
a, b

(array([3, 2, 1, 0]), array([-1, 10, -1, 11]))

In [51]:
np.column_stack((a, b))

array([[ 3, -1],
       [ 2, 10],
       [ 1, -1],
       [ 0, 11]])

Although `a.T` is same as `a` for any 1D array `a` ([see why][1]), we can take transpose of `a` by slicing it with an extra dimension ([discussed above](#Indexing)). But, it's not necessary to do so.

[1]: https://stackoverflow.com/a/5954747/7263373

In [52]:
a[:, np.newaxis]

array([[3],
       [2],
       [1],
       [0]])

### Array Views (Shallow Copy) 

A view is a numpy array that holds reference to the elements of another array. Slices returns views.

In [53]:
x = c.view()
type(x), x is c, x.base is c, x.flags.owndata

(numpy.ndarray, False, True, False)

In [54]:
x = x.ravel()
x

array([  1,   2,   3,   9,   2,   4,   3,   0,  -1,   4,   7,  -5,   5,
         0,  -5,   2,   1,   8,   0,   0,   1, -15,   3,  11])

In [55]:
x[0] = 4 # changes c's data
c

array([[[[  4,   2,   3],
         [  9,   2,   4]],

        [[  3,   0,  -1],
         [  4,   7,  -5]]],


       [[[  5,   0,  -5],
         [  2,   1,   8]],

        [[  0,   0,   1],
         [-15,   3,  11]]]])

In [56]:
y = x[...] # returns a view of x, similar to x[:]
y.shape = 4, -1
y, x

(array([[  4,   2,   3,   9,   2,   4],
        [  3,   0,  -1,   4,   7,  -5],
        [  5,   0,  -5,   2,   1,   8],
        [  0,   0,   1, -15,   3,  11]]),
 array([  4,   2,   3,   9,   2,   4,   3,   0,  -1,   4,   7,  -5,   5,
          0,  -5,   2,   1,   8,   0,   0,   1, -15,   3,  11]))

In [57]:
y[0, 0] = 10 # changes c again
c

array([[[[ 10,   2,   3],
         [  9,   2,   4]],

        [[  3,   0,  -1],
         [  4,   7,  -5]]],


       [[[  5,   0,  -5],
         [  2,   1,   8]],

        [[  0,   0,   1],
         [-15,   3,  11]]]])

As we've seen [above](#Shape-modifying-operations), deep copy can be made using the standard `array` function. Another way is to use the copy function.

In [58]:
x = y.copy()
x is a, x.base is a, x.flags.owndata

(False, False, True)

## Understanding Broadcasting
During broadcasting, the last dimensions of the two arrays are compared. If both are equal or one of them is one, then we move forward, else an exception is raised. The dimension with 1 element only is scaled to match with the other one. Let's see an examples.

|Array|Shape|
|:---|---:|
|x|2x1x5|
|y|   3x1|
|x + y| 2x3x5|

In [59]:
x = np.arange(10).reshape(2, 1, 5)
y = np.linspace(0, 1, 3).reshape(3, 1)
print(x)
print("-"*16)
print(y)
print("-"*16)
print(x + y)

[[[0 1 2 3 4]]

 [[5 6 7 8 9]]]
----------------
[[0. ]
 [0.5]
 [1. ]]
----------------
[[[ 0.   1.   2.   3.   4. ]
  [ 0.5  1.5  2.5  3.5  4.5]
  [ 1.   2.   3.   4.   5. ]]

 [[ 5.   6.   7.   8.   9. ]
  [ 5.5  6.5  7.5  8.5  9.5]
  [ 6.   7.   8.   9.  10. ]]]


Let's see how this works. 

First `y` is stretched to become a `3x5` array. Thus `y` becomes
```python
[[0. , 0. , 0. , 0. , 0. ],
 [0.5, 0.5, 0.5, 0.5, 0.5],
 [1. , 1. , 1. , 1. , 1. ]]
```
Then we add an extra outer dimension (first dimension) to `y`. Then, it is stretched to a `2x3x5` array.
```python
[[[0.   0.   0.   0.   0. ]
  [0.5  0.5  0.5  0.5  0.5]
  [1.   1.   1.   1.   1. ]]

 [[0.   0.   0.   0.   0. ]
  [0.5  0.5  0.5  0.5  0.5]
  [1.   1.   1.   1.   1. ]]]
```
Similarly, `x` is scaled to a `2x3x5` array. Therefore, `x` becomes
```python
[[[0., 1., 2., 3., 4.],
  [0., 1., 2., 3., 4.],
  [0., 1., 2., 3., 4.]],

 [[5., 6., 7., 8., 9.],
  [5., 6., 7., 8., 9.],
  [5., 6., 7., 8., 9.]]]
```
The addition from here is pretty straightforward. Of course, the stretching/scaling is hypothetical. NumPy is smart enought to not make duplicates.

### Advanced Indexing features

Next, we discuss advanced indexing features provided by NumPy not available in conventional python lists.

In [60]:
x = np.arange(15) * 2
i = [0, 1, 5, 0, 2] # list of indices
x[i]

array([ 0,  2, 10,  0,  4])

In [61]:
ii = np.array([[0, 1, 0], [1, 4, 3]]) # multidimensional index arrays
x[ii]

array([[0, 2, 0],
       [2, 8, 6]])

We have to use numpy array for the multidimensional index list otherwise NumPy throws an exception.

Here, `ii` specified the indices for the first dimension of the i/p array. We can see it more clearly by doing same on multidimensional array.

In [62]:
x = np.arange(50).reshape(-1, 10) # ith row start with 10*i and ends with 10*i + 9
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [63]:
x[ii]

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]])

We can also specify an array of indices for each dimension like we did before for single indices.

In [64]:
i = np.array([[0, 2], [3, 4]]) # First dimension indices, corresponds to [0th, 2nd] and [3rd, 4th] rows
x[i]

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]])

In [65]:
j = np.array([[5, 5], [0, 8]]) # Second dimension indices, corresponds to columns
x[:,j]

array([[[ 5,  5],
        [ 0,  8]],

       [[15, 15],
        [10, 18]],

       [[25, 25],
        [20, 28]],

       [[35, 35],
        [30, 38]],

       [[45, 45],
        [40, 48]]])

And finally

In [66]:
x[i, j] # equivalent to x[(i, j)] or x[l] where l = [i, j]

array([[ 5, 25],
       [30, 48]])

In [67]:
x[i, j] = -1 # Assignment still works
x

array([[ 0,  1,  2,  3,  4, -1,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, -1, 26, 27, 28, 29],
       [-1, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, -1, 49]])

We can also index with boolean arrays where each elements specifies whether or not to choose the particular dimension/element.

In [68]:
y = x == -1 # Of same shape as x
x[y]

array([-1, -1, -1, -1])

In [69]:
x[y] = 50
x

array([[ 0,  1,  2,  3,  4, 50,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 50, 26, 27, 28, 29],
       [50, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 50, 49]])