# Python's scientific libraries

Following is my attempt to interactively learn how to use popular libraries like numpy, scipy, matplotlib, etc. I will code and try to explore various APIs provided by these awesome libraries.

## What is NumPy?

NumPy is a python library for scientific computations. It provides multidimensional array support with fast operarions on it using compiled C code. NumPy arrays are instances of `ndarray` which are homogenous multidimensional arrays.

## Features of NumPy

1. ##### Vectorization
In numpy, most of the code resembles standard mathematical operations rather than be composed of messy `for loops`. For example, the product of two arrays in numpy is taken as follows:
$$c = a * b$$
Where c is the resultant array with $c[i] = a[i] * b[i]$.
2. ##### Broadcasting
Operations in numpy are of implicit element by element type as seen above. It refers to how numpy performs operations between arrays of different shapes. To do this, numpy broadcasts the smaller array to make it compatible with the larger one following the rules mentioned [here][1].

[1]: https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#module-numpy.doc.broadcasting

## Terminologies

1. NumPy arrays known as `ndarray` are also aliased by the name `array`.
2. The dimensions are referred to as axes.

## Basics
Let's start with some basic code.

In [12]:
import numpy as np
a = np.array([1, 2, 4])
a

array([1, 2, 4])

In [31]:
a.shape, a.ndim, a.size, a.dtype, a.itemsize, a.data # attributes of ndarray class

((3,), 1, 3, dtype('int64'), 8, <memory at 0x7f8aad4fbac8>)

In [17]:
type(a)

numpy.ndarray

In [32]:
b = np.array([
    [1, 3, 4], [1, 0 , -1] # a 2-d array
], dtype = np.int8)        # np data types include intx, floatx, uintx (unsigned), bool_, complex64, complex128
                           # where x is number of bits per element: 8, 16, ...

In [30]:
b.shape, b.size, b.itemsize

((2, 3), 6, 1)

In [35]:
np.zeros([2,3]) # creates a 2 x 3 array and fills it with 0s with dtype = float64

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones([1, 7], dtype = np.bool_)

array([[ True,  True,  True,  True,  True,  True,  True]])

In [41]:
np.empty([1, 3]) # randomly initialized contents

array([[6.92847242e-310, 6.92845925e-310, 6.92845925e-310]])

In [45]:
np.arange(23) == np.array(range(23)) # arange() creates array similar to python's range

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

^Even the comparison operation is vectorized...

In [51]:
np.arange(0, 1, 0.333333333333333333) # arange unlike range accepts float arguments

array([0.        , 0.33333333, 0.66666667])

although, linspace is preferred over arange because of limitations of floating precision.

In [53]:
np.linspace(0, 1, 4) # third argument denotes the size of result array

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [61]:
np.zeros_like(b) # creates zero array with the dimensions of b

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [62]:
np.full([2, 1], 10)

array([[10],
       [10]])

In [67]:
c = np.array([
    [
        [[1, 2, 3], [9, 2, 4]],            # This shows how np arrays are printed
        [[3, 0, -1], [4, 7, -5]] 
    ],
    [
        [[5, 0, -5], [2, 1, 8]],
        [[0, 0, 1], [-15, 3, 11]]
    ]
])
print(c)

[[[[  1   2   3]
   [  9   2   4]]

  [[  3   0  -1]
   [  4   7  -5]]]


 [[[  5   0  -5]
   [  2   1   8]]

  [[  0   0   1]
   [-15   3  11]]]]


As we've seen before all operations are performed elementwise. Let's try out a few...

In [69]:
x = 3
y = np.arange(5)
x * y                # x scaled before taking product

array([ 0,  3,  6,  9, 12])

In [72]:
x = np.linspace(4, 5, 5) - 4
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [77]:
x + y, x - y, x * y, x < y, y / 2

(array([0.  , 1.25, 2.5 , 3.75, 5.  ]),
 array([ 0.  , -0.75, -1.5 , -2.25, -3.  ]),
 array([0.  , 0.25, 1.  , 2.25, 4.  ]),
 array([False,  True,  True,  True,  True]),
 array([0. , 0.5, 1. , 1.5, 2. ]))

In [83]:
x = np.linspace(1, 2, 6)
x, x / (x * 0.5)

(array([1. , 1.2, 1.4, 1.6, 1.8, 2. ]), array([2., 2., 2., 2., 2., 2.]))

We can do matrix multiplication using `@` operator or `dot` function.

## Understanding Broadcasting
During broadcasting, the last dimensions of the two arrays are compared. If both are equal or one of them is one, then we move forward, else and exception is raised. The dimension with 1 element only is scaled to match with the other one. Let's see some examples.